import { useState } from 'react'

export default function DisclaimerModal({ onAccept }) {
  const [ticked, setTicked] = useState(false)

  function handleAccept() {
    localStorage.setItem('devcheck_disclaimer_accepted', 'true')
    onAccept()
  }

  return (
    <div style={{position:'fixed',inset:0,background:'rgba(0,0,0,0.85)',zIndex:9998,display:'flex',alignItems:'center',justifyContent:'center',padding:'24px 16px',overflowY:'auto'}}>
      <div style={{background:'#1C1C1C',border:'1px solid #2E2E2E',borderRadius:12,maxWidth:620,width:'100%',padding:'32px',display:'flex',flexDirection:'column',gap:20}}>

        <div>
          <div style={{fontFamily:"'Cormorant Garamond',serif",fontSize:24,fontWeight:700,color:'#F2F2F2',marginBottom:4}}>Important Disclaimer</div>
          <div style={{fontSize:12,color:'#6B7280'}}>Please read carefully before using DevCheck</div>
        </div>

        {/* Scrollable disclaimer text */}
        <div style={{background:'#111111',border:'1px solid #2E2E2E',borderRadius:8,padding:'16px 18px',maxHeight:320,overflowY:'auto',fontSize:13,color:'#A0A8B0',lineHeight:1.8}}>
          <p style={{marginBottom:12}}>
            DevCheck is a property development feasibility tool designed to provide general indicative assessments only. The information, analysis, and outputs generated by DevCheck do not constitute financial advice, investment advice, planning advice, legal advice, or a valuation.
          </p>
          <p style={{marginBottom:12}}>
            The accuracy of any output is entirely dependent on the accuracy of the information you provide. Outputs are indicative only and may not reflect current market conditions, council requirements, planning regulations, infrastructure costs, or other material factors relevant to a specific development.
          </p>
          <p style={{marginBottom:12}}>
            Before making any financial, development, or investment decision, you should obtain independent advice from qualified professionals including a licensed valuer, town planner, licensed builder or quantity surveyor, financial adviser or accountant, and a solicitor or conveyancer.
          </p>
          <p style={{marginBottom:12}}>
            Development potential identified through DevCheck is indicative only. Zoning, overlay controls, development approval requirements, and council policies change frequently. Always verify current planning rules directly with the relevant council or a qualified town planner before proceeding.
          </p>
          <p style={{marginBottom:12}}>
            To the maximum extent permitted by law, Clinton Barker Property and the operators of DevCheck accept no liability for any loss, damage, or expense arising directly or indirectly from reliance on any output generated by this tool. Use of DevCheck is entirely at your own risk.
          </p>
          <p>
            Assessments produced by DevCheck are generated by an artificial intelligence system and may contain errors, omissions, or inaccuracies. No output should be treated as definitive or relied upon without independent verification.
          </p>
        </div>

        {/* Checkbox */}
        <label style={{display:'flex',gap:12,alignItems:'flex-start',cursor:'pointer'}}>
          <input
            type="checkbox"
            checked={ticked}
            onChange={e => setTicked(e.target.checked)}
            style={{marginTop:3,accentColor:'#34A86E',width:16,height:16,flexShrink:0}}
          />
          <span style={{fontSize:13,color:'#F2F2F2',lineHeight:1.6}}>
            I have read and understood this disclaimer and agree to use DevCheck for general guidance purposes only.
          </span>
        </label>

        {/* Button */}
        <div>
          <button
            onClick={handleAccept}
            disabled={!ticked}
            style={{
              width:'100%',padding:'13px',borderRadius:8,border:'none',
              background: ticked ? '#34A86E' : '#2E2E2E',
              color: ticked ? '#fff' : '#6B7280',
              fontSize:14,fontWeight:600,cursor:ticked?'pointer':'not-allowed',
              fontFamily:"'DM Sans',sans-serif",letterSpacing:'.02em',
              transition:'background .2s, color .2s'
            }}
          >
            Continue to DevCheck →
          </button>
        </div>

      </div>
    </div>
  )
}
